version: "3.9"

services:
  gateway:
    image: asia-northeast3-docker.pkg.dev/phoding/phoding/gateway:latest
    container_name: phoding-gateway
    env_file:
      - ./gateway.env
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - phoding

  frontend:
    image: asia-northeast3-docker.pkg.dev/phoding/phoding/frontend:latest
    container_name: phoding-frontend
    env_file:
      - ./frontend.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - phoding

  nginx:
    image: nginx:1.27-alpine
    container_name: phoding-nginx
    depends_on:
      - frontend
      - gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - phoding

networks:
  phoding:
    driver: bridge
