version: "3.9"

services:
  gateway:
    build:
      context: ..
      dockerfile: deploy/gateway.Dockerfile
    container_name: codemore-gateway
    env_file:
      - ./gateway.env
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - codemore

  frontend:
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
    container_name: codemore-frontend
    env_file:
      - ./frontend.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - codemore

  nginx:
    image: nginx:1.27-alpine
    container_name: codemore-nginx
    depends_on:
      - frontend
      - gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - codemore

networks:
  codemore:
    driver: bridge

