version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: phoding-postgres-dev
    environment:
      POSTGRES_DB: phoding
      POSTGRES_USER: phoding
      POSTGRES_PASSWORD: phoding_dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - phoding-dev

  gateway:
    image: node:22-alpine
    container_name: phoding-gateway-dev
    working_dir: /workspace/gateway
    env_file:
      - ./gateway.env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "1"
      DATABASE_URL: postgresql://phoding:phoding_dev_password@postgres:5432/phoding
    volumes:
      - ../gateway:/workspace/gateway
      - ../workspace:/workspace/workspace
      - gateway_node_modules:/workspace/gateway/node_modules
    command: >
      sh -c "apk add --no-cache openssl && npm install && npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - phoding-dev
    depends_on:
      - postgres

  frontend:
    image: node:22-alpine
    container_name: phoding-frontend-dev
    working_dir: /workspace/frontend
    env_file:
      - ./frontend.env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "1"
      NEXT_WEBPACK_USEPOLLING: "1"
    volumes:
      - ../frontend:/workspace/frontend
      - frontend_node_modules:/workspace/frontend/node_modules
    command: >
      sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - gateway
    networks:
      - phoding-dev

networks:
  phoding-dev:
    driver: bridge

volumes:
  frontend_node_modules:
  gateway_node_modules:
  postgres_data:
